export const DEPARTMENTS = [
    { value: "CSE", label: "CSE" },
    { value: "CSE-AIML", label: "CSE-AIML" },
    { value: "CSE-AIDS", label: "CSE-AIDS" },
    { value: "CSE-DS", label: "CSE-DS" },
    { value: "CSIT", label: "CSIT" },
    { value: "CSE-IOT", label: "CSE-IOT" },
    { value: "ECE", label: "ECE" },
    { value: "EE", label: "EE" },
    { value: "ME", label: "ME" },
    { value: "Civil", label: "Civil" },
    { value: "BCA", label: "BCA" },
    { value: "MCA", label: "MCA" },
    { value: "B.Pharma", label: "B.Pharma" },
    { value: "Polytechnic", label: "Polytechnic" },
    { value: "Diploma", label: "Diploma" },
    { value: "MBA", label: "MBA" },
    { value: "BBA", label: "BBA" },
];
