-- CGU Connect Hub - Database Migration Script
-- Run this in your Supabase SQL Editor Dashboard
-- This script adds the missing saved_posts table and fixes all RLS policies

-- ============================================
-- STEP 1: Create saved_posts table
-- ============================================

create table if not exists public.saved_posts (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  post_id bigint references public.posts(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, post_id)
);

-- Enable RLS on saved_posts
alter table public.saved_posts enable row level security;

-- ============================================
-- STEP 2: Drop old permissive RLS policies
-- ============================================

-- Users table policies
drop policy if exists "Public users are viewable by everyone" on public.users;
drop policy if exists "Users can insert their own profile" on public.users;
drop policy if exists "Users can update own profile" on public.users;

-- Posts table policies
drop policy if exists "Public posts are viewable by everyone" on public.posts;
drop policy if exists "Authenticated users can insert posts" on public.posts;
drop policy if exists "Users can update own posts" on public.posts;

-- Likes table policies
drop policy if exists "Public likes are viewable by everyone" on public.likes;
drop policy if exists "Authenticated users can insert likes" on public.likes;
drop policy if exists "Users can delete own likes" on public.likes;

-- Comments table policies
drop policy if exists "Public comments are viewable by everyone" on public.comments;
drop policy if exists "Authenticated users can insert comments" on public.comments;

-- Notifications table policies
drop policy if exists "Users can view their own notifications" on public.notifications;
drop policy if exists "System can insert notifications" on public.notifications;

-- ============================================
-- STEP 3: Create new secure RLS policies
-- ============================================

-- Users table policies
create policy "Users are viewable by everyone" on public.users for select using (true);
create policy "Users can insert their own profile" on public.users for insert with check (auth.uid()::text = email);
create policy "Users can update own profile" on public.users for update using (auth.uid()::text = email);
create policy "Users can delete own profile" on public.users for delete using (auth.uid()::text = email);

-- Posts table policies
create policy "Posts are viewable by everyone" on public.posts for select using (true);
create policy "Users can insert own posts" on public.posts for insert with check (
  exists (select 1 from public.users where id = user_id and email = auth.uid()::text)
);
create policy "Users can update own posts" on public.posts for update using (
  exists (select 1 from public.users where id = user_id and email = auth.uid()::text)
);
create policy "Users can delete own posts" on public.posts for delete using (
  exists (select 1 from public.users where id = user_id and email = auth.uid()::text)
);

-- Likes table policies
create policy "Likes are viewable by everyone" on public.likes for select using (true);
create policy "Users can insert own likes" on public.likes for insert with check (
  exists (select 1 from public.users where id = user_id and email = auth.uid()::text)
);
create policy "Users can delete own likes" on public.likes for delete using (
  exists (select 1 from public.users where id = user_id and email = auth.uid()::text)
);

-- Comments table policies
create policy "Comments are viewable by everyone" on public.comments for select using (true);
create policy "Users can insert own comments" on public.comments for insert with check (
  exists (select 1 from public.users where id = user_id and email = auth.uid()::text)
);
create policy "Users can update own comments" on public.comments for update using (
  exists (select 1 from public.users where id = user_id and email = auth.uid()::text)
);
create policy "Users can delete own comments" on public.comments for delete using (
  exists (select 1 from public.users where id = user_id and email = auth.uid()::text)
);

-- Notifications table policies
create policy "Users can view own notifications" on public.notifications for select using (
  exists (select 1 from public.users where id = user_id and email = auth.uid()::text)
);
create policy "System can insert notifications" on public.notifications for insert with check (true);
create policy "Users can update own notifications" on public.notifications for update using (
  exists (select 1 from public.users where id = user_id and email = auth.uid()::text)
);
create policy "Users can delete own notifications" on public.notifications for delete using (
  exists (select 1 from public.users where id = user_id and email = auth.uid()::text)
);

-- Follows table policies
create policy "Follows are viewable by everyone" on public.follows for select using (true);
create policy "Users can insert own follows" on public.follows for insert with check (
  exists (select 1 from public.users where id = follower_id and email = auth.uid()::text)
);
create policy "Users can delete own follows" on public.follows for delete using (
  exists (select 1 from public.users where id = follower_id and email = auth.uid()::text)
);

-- Conversations table policies
create policy "Users can view own conversations" on public.conversations for select using (
  exists (
    select 1 from public.users 
    where (id = participant1_id or id = participant2_id) 
    and email = auth.uid()::text
  )
);
create policy "Users can create conversations" on public.conversations for insert with check (
  exists (select 1 from public.users where id = participant1_id and email = auth.uid()::text)
);
create policy "Users can update own conversations" on public.conversations for update using (
  exists (
    select 1 from public.users 
    where (id = participant1_id or id = participant2_id) 
    and email = auth.uid()::text
  )
);

-- Messages table policies
create policy "Users can view messages in own conversations" on public.messages for select using (
  exists (
    select 1 from public.conversations c
    join public.users u on (u.id = c.participant1_id or u.id = c.participant2_id)
    where c.id = conversation_id and u.email = auth.uid()::text
  )
);
create policy "Users can insert messages in own conversations" on public.messages for insert with check (
  exists (
    select 1 from public.conversations c
    join public.users u on (u.id = c.participant1_id or u.id = c.participant2_id)
    where c.id = conversation_id and u.email = auth.uid()::text
  )
);
create policy "Users can update own messages" on public.messages for update using (
  exists (select 1 from public.users where id = sender_id and email = auth.uid()::text)
);
create policy "Users can delete own messages" on public.messages for delete using (
  exists (select 1 from public.users where id = sender_id and email = auth.uid()::text)
);

-- Saved posts table policies
create policy "Users can view own saved posts" on public.saved_posts for select using (
  exists (select 1 from public.users where id = user_id and email = auth.uid()::text)
);
create policy "Users can insert own saved posts" on public.saved_posts for insert with check (
  exists (select 1 from public.users where id = user_id and email = auth.uid()::text)
);
create policy "Users can delete own saved posts" on public.saved_posts for delete using (
  exists (select 1 from public.users where id = user_id and email = auth.uid()::text)
);

-- ============================================
-- VERIFICATION QUERIES (optional - run to check)
-- ============================================

-- Check if saved_posts table was created
-- SELECT * FROM information_schema.tables WHERE table_name = 'saved_posts';

-- Check RLS is enabled on all tables
-- SELECT tablename, rowsecurity FROM pg_tables WHERE schemaname = 'public';

-- View all policies
-- SELECT schemaname, tablename, policyname, permissive, cmd 
-- FROM pg_policies 
-- WHERE schemaname = 'public'
-- ORDER BY tablename, policyname;
