-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Create users table
create table public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  email text unique not null,
  password text, -- Optional for OAuth users
  avatar text,
  display_name text,
  bio text,
  semester text,
  department text,
  profile_setup_complete boolean default false,
  password_setup_complete boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create posts table
create table public.posts (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  image text not null,
  caption text,
  likes_count int default 0,
  comments_count int default 0,
  pinned boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create likes table
create table public.likes (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  post_id bigint references public.posts(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, post_id)
);

-- Create comments table
create table public.comments (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  post_id bigint references public.posts(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create notifications table
create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  type text not null check (type in ('like', 'comment', 'follow')),
  from_user_id bigint references public.users(id) on delete cascade not null,
  post_id bigint references public.posts(id) on delete cascade,
  message text not null,
  read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create follows table
create table public.follows (
  id bigint generated by default as identity primary key,
  follower_id bigint references public.users(id) on delete cascade not null,
  following_id bigint references public.users(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(follower_id, following_id)
);

-- Create conversations table
create table public.conversations (
  id bigint generated by default as identity primary key,
  participant1_id bigint references public.users(id) on delete cascade not null,
  participant2_id bigint references public.users(id) on delete cascade not null,
  last_message_id bigint, -- Circular reference, handled carefully or ignored in FK for simplicity
  last_message_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references public.conversations(id) on delete cascade not null,
  sender_id bigint references public.users(id) on delete cascade not null,
  content text not null,
  message_type text default 'text' check (message_type in ('text', 'image', 'video')),
  media_url text,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.users enable row level security;
alter table public.posts enable row level security;
alter table public.likes enable row level security;
alter table public.comments enable row level security;
alter table public.notifications enable row level security;
alter table public.follows enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;

-- Create policies (OPEN ACCESS FOR NOW TO FIX IMMEDIATE ISSUES)
-- In a real production app, you would lock this down further.

create policy "Public users are viewable by everyone" on public.users for select using (true);
create policy "Users can insert their own profile" on public.users for insert with check (true);
create policy "Users can update own profile" on public.users for update using (true);

create policy "Public posts are viewable by everyone" on public.posts for select using (true);
create policy "Authenticated users can insert posts" on public.posts for insert with check (true); -- simplified
create policy "Users can update own posts" on public.posts for update using (true); -- simplified

create policy "Public likes are viewable by everyone" on public.likes for select using (true);
create policy "Authenticated users can insert likes" on public.likes for insert with check (true);
create policy "Users can delete own likes" on public.likes for delete using (true);

create policy "Public comments are viewable by everyone" on public.comments for select using (true);
create policy "Authenticated users can insert comments" on public.comments for insert with check (true);

create policy "Users can view their own notifications" on public.notifications for select using (true); -- simplified
create policy "System can insert notifications" on public.notifications for insert with check (true); -- simplified

-- Storage buckets (if needed, but handled via UI usually)
-- insert into storage.buckets (id, name) values ('posts', 'posts');
-- insert into storage.buckets (id, name) values ('avatars', 'avatars');
